import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "IdeaZVault",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-[#e0cbb0]/90 ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div>
          <Navbar />
        </div>
        <div>
        {children}
        </div>
        <div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
